name: Deploy Hugo Site

on:
  # 在推送到 main 分支时触发
  push:
    branches:
      - main
  # 允许你手动在 Actions 页面触发这个工作流
  workflow_dispatch:

# 设置任务的默认权限
permissions:
  contents: write # 允许 actions-gh-pages 推送到仓库

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # --- 第 1 步: 检出源码 ---
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # 必须，用来拉取主题
          fetch-depth: 0         # 必须，用来获取完整的 git 历史

      # --- 第 2 步: 设置 Hugo ---
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # 必须，为了 Sass/SCSS

      # --- 第 3 步: 设置 Node.js ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 使用一个稳定的 LTS 版本
          cache: 'npm'

      # --- 第 4 步: 安装依赖 ---
      - name: Install Node.js dependencies
        run: npm ci

      # --- 第 5 步: 构建网站 ---
      - name: Build site with Hugo
        run: hugo --cleanDestinationDir

      # --- 第 6 步: 更新 Algolia 索引 ---
      - name: Update Algolia index
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_INDEX_FILE: public/algolia.json
        run: npm run algolia

      # --- 第 7 步: 部署到 GitHub Pages ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
          publish_dir: ./public
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Build and deploy from GitHub Actions: ${{ github.sha }}"

